project:
  type: website

website:
  title: "Ciência de Dados"
  site-url: "https://gilbertosassi.quarto.pub/cienciadedados/"
  body-footer: "&#169; 2024 **`R` para Ciência de Dados <br>&#128420;** by Carolina Paraíba e Gilberto Sassi"
  navbar:
    logo: assets/r.png
    left:
      - href: index.qmd
        text: Home
      - href: paginas/inscricoes.qmd
        text: Inscrições
      - href: paginas/catalogo.qmd
        text: "Cursos oferecidos"
      - href: paginas/material.qmd
        text: "Material"
      - href: paginas/cade.qmd
        text: CADE
      - href: paginas/eventos.qmd
        text: Eventos
      - href: paginas/equipe.qmd
        text: Equipe
      - text: "Editais"
        menu:
          - href: paginas/editais/editais-abertos.qmd
            text: "Editais abertos"
          - href: paginas/editais/editais-2023.qmd
            text: "Editais encerrados"
      - href: paginas/contato.qmd
        text: 'Contato'


format:
  html:
    pandoc_args: ["--variable", "footnotes-appear-in-blocks", "--variable", "footnote-placement", "para"]
    lang: pt-br
    include-in-header: assets/header.html
    theme:
      light: spacelab
      dark: superhero
    css: assets/styles.css
    toc: true
