project:
  type: website

website:
  open-graph:
    locale: pt_BR
    site-name: "Ciência de Dados"
  title: "Ciência de Dados"
  google-analytics:
    tracking-id: G-0WD3PSV647
    anonymize-ip: true
  site-url: "https://ufba.netlify.app/"
  body-footer: "&#169; 2024 **Ciência de Dados <br>&#128420;** by Carolina Paraíba e Gilberto Sassi"
  navbar:
    logo: assets/r.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Inscrições"
        href: paginas/inscricoes.qmd
      - text: "Cursos oferecidos"
        href: paginas/catalogo.qmd
      - text: "Material"
        href: paginas/material.qmd
      # - href: paginas/cade.qmd
      #   text: CADE
      # - href: paginas/eventos.qmd
      #   text: Eventos
      - text: Editais
        href: paginas/editais-2024.qmd
      - text: "Equipe"
        href: paginas/equipe.qmd
      - text: 'Contato'
        href: paginas/contato.qmd

format:
  html:
    pandoc_args: ["--variable", "footnotes-appear-in-blocks", "--variable", "footnote-placement", "para"]
    lang: pt-br
    include-in-header: assets/header.html
    theme:
      light: spacelab
      dark: superhero
    css: assets/styles.css
    toc: true
